#ifndef CUDAFINGERPRINTING_MINUTIACONSTANTS
#define CUDAFINGERPRINTING_MINUTIACONSTANTS

#define DESCRIPTOR_RADIUS 70 //TODO
#define COMPARE_RADIUS 5
#define FENG_CONSTANT 0.64
#define FENG_ANGLE 1.74532925

#endif