#ifndef CUDAFINGERPRINTING_MINUTIACONSTANTS
#define CUDAFINGERPRINTING_MINUTIACONSTANTS

#define DESCRIPTOR_RADIUS 70 //TODO: count radius (width and heigth of picture)
#define COMPARE_RADIUS 5
#define FENG_CONSTANT 0.64f //
#define FENG_ANGLE 1.74532925f
#define DESC_PER_BLOCK 4
#define DESC_BLOCK_SIZE 16

#endif