//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CUDAFingerprinting.FeatureExtraction.Tests {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CUDAFingerprinting.FeatureExtraction.Tests.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_1 {
            get {
                object obj = ResourceManager.GetObject("_1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _101_8 {
            get {
                object obj = ResourceManager.GetObject("_101_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _19_4 {
            get {
                object obj = ResourceManager.GetObject("_19_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1test {
            get {
                object obj = ResourceManager.GetObject("_1test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_6 {
            get {
                object obj = ResourceManager.GetObject("_2_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_6Test {
            get {
                object obj = ResourceManager.GetObject("_2_6Test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _29_4 {
            get {
                object obj = ResourceManager.GetObject("_29_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _44_8 {
            get {
                object obj = ResourceManager.GetObject("_44_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap binarizated1 {
            get {
                object obj = ResourceManager.GetObject("binarizated1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connectedness {
            get {
                object obj = ResourceManager.GetObject("connectedness", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap connectedness2 {
            get {
                object obj = ResourceManager.GetObject("connectedness2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap egor {
            get {
                object obj = ResourceManager.GetObject("egor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap H {
            get {
                object obj = ResourceManager.GetObject("H", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap idealH {
            get {
                object obj = ResourceManager.GetObject("idealH", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap line {
            get {
                object obj = ResourceManager.GetObject("line", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ManPic {
            get {
                object obj = ResourceManager.GetObject("ManPic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 35
        ///229 39 2,449438
        ///147 71 -0,2606235
        ///234 84 2,186548
        ///128 99 -0,1800297
        ///56 100 3,320978
        ///101 101 3,076542
        ///73 122 0,0976407
        ///46 125 0,4868098
        ///166 129 2,258028
        ///65 167 0,9414192
        ///143 179 -1,169901
        ///180 187 1,795628
        ///104 191 2,185517
        ///98 207 1,661734
        ///161 211 -1,227642
        ///175 223 -1,274908
        ///150 234 -0,7967598
        ///79 236 1,827496
        ///98 238 -1,025437
        ///169 253 2,606827
        ///195 253 -1,03603
        ///212 268 -0,5588933
        ///180 269 -0,3411583
        ///162 270 -0,1575346
        ///29 280 1,938925
        ///108 291 -0,27722
        ///189 295 -0,2001203
        ///69 297 -0,714 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string minutia1_1 {
            get {
                return ResourceManager.GetString("minutia1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minutia1_11 {
            get {
                object obj = ResourceManager.GetObject("minutia1_11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 40
        ///68 139 0,2194806
        ///32 148 0,6078865
        ///26 152 3,770413
        ///135 160 -0,2267988
        ///115 170 3,045842
        ///50 176 0,5943582
        ///40 180 3,890526
        ///125 187 -0,1259777
        ///229 197 2,247919
        ///16 202 1,128807
        ///82 221 0,6505191
        ///72 234 4,275165
        ///70 237 1,172025
        ///145 242 2,159719
        ///222 243 1,942959
        ///21 256 1,375556
        ///111 256 0,1117383
        ///71 257 4,476734
        ///86 262 1,347036
        ///112 262 0,4589748
        ///237 264 -1,229638
        ///121 266 -0,2372485
        ///110 274 4,390638
        ///148 282 -1,31581
        ///116 286 1,563221
        ///124 286 1,711413
        ///52 287 4,699571
        ///52 289 1,557979
        ///131 2 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string minutia2_2 {
            get {
                return ResourceManager.GetString("minutia2_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minutia2_21 {
            get {
                object obj = ResourceManager.GetObject("minutia2_21", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 55
        ///174 22 -0,2742747
        ///147 29 3,056704
        ///85 31 0,5443162
        ///74 36 3,812626
        ///160 54 -0,1989372
        ///115 83 0,5228161
        ///173 106 2,092157
        ///50 111 1,295713
        ///106 114 4,390638
        ///142 122 -0,08609541
        ///114 126 1,336164
        ///79 144 4,646335
        ///143 147 1,47047
        ///149 148 1,65556
        ///174 149 -1,36003
        ///79 152 1,554738
        ///157 155 1,801337
        ///208 160 1,683152
        ///182 165 1,649681
        ///117 166 4,712389
        ///124 166 4,680852
        ///58 170 1,516744
        ///118 173 1,661456
        ///156 183 1,71085
        ///235 184 1,663728
        ///129 187 1,753059
        ///159 187 1,553646
        ///140 193 2,046371
        ///150 193 -1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string minutia2_3 {
            get {
                return ResourceManager.GetString("minutia2_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minutia2_31 {
            get {
                object obj = ResourceManager.GetObject("minutia2_31", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 56
        ///213 31 2,250281
        ///116 36 -0,2183136
        ///75 59 0,4150722
        ///208 80 1,963495
        ///134 89 2,213169
        ///222 99 -1,153479
        ///61 103 4,473474
        ///103 108 0,1931686
        ///77 109 1,298471
        ///110 112 -0,0488134
        ///103 114 3,450576
        ///111 129 4,679698
        ///139 130 -1,246041
        ///99 136 4,696769
        ///169 136 1,801229
        ///124 139 1,855349
        ///101 141 1,629351
        ///149 145 1,685667
        ///26 146 1,53731
        ///226 146 1,840449
        ///96 150 1,669494
        ///90 153 -1,483039
        ///122 157 -1,297534
        ///201 161 1,718706
        ///93 162 1,795426
        ///67 178 1,7454
        ///122 178 -0,7196638
        ///172 188 1,584216
        ///126 192 -1 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string minutia2_6 {
            get {
                return ResourceManager.GetString("minutia2_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minutia2_61 {
            get {
                object obj = ResourceManager.GetObject("minutia2_61", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap patt {
            get {
                object obj = ResourceManager.GetObject("patt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SampleFinger {
            get {
                object obj = ResourceManager.GetObject("SampleFinger", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap skeleton {
            get {
                object obj = ResourceManager.GetObject("skeleton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small {
            get {
                object obj = ResourceManager.GetObject("small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small1 {
            get {
                object obj = ResourceManager.GetObject("small1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap test {
            get {
                object obj = ResourceManager.GetObject("test", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap verySmall {
            get {
                object obj = ResourceManager.GetObject("verySmall", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap verySmall2 {
            get {
                object obj = ResourceManager.GetObject("verySmall2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap X {
            get {
                object obj = ResourceManager.GetObject("X", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
